### ISSUE TITLE
I want to compress video file

### ISSUE THREAD

**Issue by junestchick** [mw99/DataCompression#6]
Hi, I want to compress video file before uploading to server, should i use this? Does it work in my case? 
Thanks

**Comment by mw99** [comment]
Hi, compressing video files is not a really good idea in general. They are already compressed as much as possible. If you are lucky you may get 1% smaller files. But they may even get bigger and it drains the battery quite a lot.
Besides that, this library it not really fit for large files, because you must load the whole file into memory. That is OK when the files are small, (< ~2MB) but video files are normally bigger.

Just upload them without compression.
